sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t 290803/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true 290803/docker-react npm run test
